Fix crash when dailer cannot write settings
java.lang.IllegalStateException: FragmentManager is already executing transactions

Change-Id: I64cec8c5c5e138338f430fc9c1a75864c065491e
Signed-off-by: Ghosuto <clash.raja10@gmail.com>